### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name PurchaselyView

### ISSUE THREAD

**Issue by Kerumen** [Purchasely/Purchasely-ReactNative#107]
I upgraded `react-native-purchasely` to `v4.3.2` and got this error:
```
Invariant Violation: Tried to register two views with the same name PurchaselyView
```

I think this is because of [this line](https://github.com/Purchasely/Purchasely-ReactNative/blob/main/purchasely/src/PLYPresentationView.tsx#L15) in `PLYPresentationView` which conflict with the main require in [PurchaselyViewManager](https://github.com/Purchasely/Purchasely-ReactNative/blob/main/purchasely/src/PurchaselyViewManager.tsx).

---
<img src="https://github.com/Purchasely/Purchasely-ReactNative/assets/5436545/904fcf2f-62e1-4e62-a28d-6a786b225e52" width="300">

**Comment by kherembourg** [comment]
Hello @Kerumen 

We do not have the issue on our side but you may be right here, thank you for the report!
I have commented the content of PurchaselyViewManager as a temporary fix as this file is not needed at the moment

We will release a new version with that change by end of week
