### ISSUE TITLE
Display Paywalls in portrait mode only

### ISSUE THREAD

**Issue by Geoffrey63** [Purchasely/Purchasely-ReactNative#33]
Hi, 
Our app is portrait mode only but when the Paywall is displayed, user can rotate his phone to display it in landscape.
Is there a way to lock the rotation on Paywall screen ? 
Thank you.

**Comment by kherembourg** [comment]
Hello,

Sorry for the very long response delay, we do not answer at the moment in the Github repository

Locking rotation is possible on Android by overriding the Activity used in the manifest and for iOS there is no solution yet

Please contact us on Intercom from our console for a follow-up support and requests

Thank you!
