### ISSUE TITLE
@purchasely/react-native-purchasely-google still in 2.6.4 even after 2.6.5 update

### ISSUE THREAD

**Issue by youssdevx** [Purchasely/Purchasely-ReactNative#43]
`@purchasely/react-native-purchasely-google` is still in **v2.6.4** whereas all other packages were updated.

@kherembourg Did you encounter an issue during the publishing of the package?

<img width="520" alt="image" src="https://user-images.githubusercontent.com/21293851/222551074-231b4229-3eaa-4b34-a4ce-7aaec1e8d4f2.png">

**Comment by kherembourg** [comment]
It has been fixed thanks!
