### ISSUE TITLE
When closing multiple views in the paywall, the last view shows a black screen (Android)

### ISSUE THREAD

**Issue by inanc-g** [Purchasely/Purchasely-ReactNative#48]
If the paywall consists of multiple stacked views, at some point when closing the views again, the bottom-most view will show a black screen on Android:
![image](https://github.com/Purchasely/Purchasely-ReactNative/assets/1510491/fece13c5-60c3-400b-919e-22f382dacec5)

**Comment by kherembourg** [comment]
Fix in 2.7.0
