### ISSUE TITLE
When navigating to a new view, the screen flashes white

### ISSUE THREAD

**Issue by inanc-g** [Purchasely/Purchasely-ReactNative#49]
When navigating to a new view inside the paywall, the screen will flash white before the content loads. Even if the background color is set to black. This is very noticable on dark apps:

https://github.com/Purchasely/Purchasely-ReactNative/assets/1510491/db031721-ca1d-45c5-82f2-beb818cc6e40

**Comment by kherembourg** [comment]
Fixed in 2.7.0
