### ISSUE TITLE
Try to present PLYProductViewController causes crash 

### ISSUE THREAD

**Issue by Geoffrey63** [Purchasely/Purchasely-ReactNative#50]
On version 2.6.8, I encounter the following crash when I press the purchase button in some conditions :

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally a view controller <Purchasely.PLYProductViewController: 0x7fb5d80db400> that is already being presented by <UIViewController: 0x7fb5edf38140>.'`

Crash occurs when i call the onProcessAction in the paywalInterceptorCallback :

```
Purchasely.setPaywallActionInterceptorCallback(result => {
  switch (result.action) {
    case PLYPaywallAction.LOGIN:
    case PLYPaywallAction.PURCHASE:
    case PLYPaywallAction.RESTORE: {

      if (!isUserAuthenticated) {
        ...
      } else {
        setupUserAccount()
          .then(userAccount => {
            Purchasely.onProcessAction(true); // <--- This causes the crash 💥 
          })
          .catch(error => {
            ...
          });
      }
      break;
    }
    case PLYPaywallAction.CLOSE:
      ...
      break;
    ...
  }
});
 ```

The same code works fine on 2.6.6 version.

**Comment by mlanoy1** [comment]
Hello @Geoffrey63, Does your paywall have a flow? I mean, does a paywall opens another paywall before purchasing something? This issue happens in those cases. we've fixed it and will be available in our next release.

**Comment by Geoffrey63** [comment]
Hello, our paywall doesn't open another paywall but it opens a modal webview for the user login. Once user is logged in, calling the onProcessAction causes the crash.

**Comment by mlanoy1** [comment]
Did you close your webview before calling `onProcessAction`?

**Comment by Geoffrey63** [comment]
Yes, the webview is closed when the onProcessAction is called.

**Comment by mlanoy1** [comment]
Does the paywall has been closed before displaying your webview? You should try to call `closePaywall()` before displaying your webview.

**Comment by Geoffrey63** [comment]
I tried to close the Paywall but i've still have a crash. 

The use case is the following :
- Open the paywall and click on a plan to purchase 
- When the login popup (system popup to log with an apple id) is displayed, click on "cancel"
- Close the paywall using the top right cross button
- Reopen the paywall and clic again on a plan to purchase => the application crashes

**Comment by mlanoy1** [comment]
It has been fixed.Available in next release

**Comment by Geoffrey63** [comment]
Great, thank you @mlanoy1 🙏🏻
