### ISSUE TITLE
Android: Various visual glitches and unable to select products on paywall

### ISSUE THREAD

**Issue by thomas-coldwell** [Purchasely/Purchasely-ReactNative#51]
Firstly, if I am not logged in I am able to access the paywall **without any issues** and view all of the products and the CTA button is visible aside from only one other issue [already reported here](https://github.com/Purchasely/Purchasely-ReactNative/issues/48) 😃

However, once I log in and return to the paywall I encounter a series of issues:
- Some screens I navigate onto with products available to purchase are not highlighted and cannot be selected, as a result the CTA button is also hidden and there is no close button on the screen (see screen recordings shared in Slack)
- Some screens I open I get an alert telling me the product is not available to purchase in my country (I am in the UK but the product is only available in Austria atm) - I would expect this is shown on ever screen I visit not just once and even then only when I press the CTA button to try and purchase that product
- When I close a particular screen in the paywall and then go to open a new one it caches the old screen and I see that previous screen instead (again see Slack for this behaviour)

These issues then fully prevent me from completing any kind of purchase of any product

This was all tested on a OnePlus 6 running Android 11

**Comment by kherembourg** [comment]
Fixed in latest version 2.7.3
