### ISSUE TITLE
App crash after closing paywall

### ISSUE THREAD

**Issue by SialB** [Purchasely/Purchasely-ReactNative#53]
We are on the latest release `2.7.0`.

On our app, we have an existing subscription for a premium plan which is working good, with custom paywalls displayed like this:
```
const presentation = await Purchasely.fetchPresentation({
  placementId: placementVendorId
});

const result = await Purchasely.presentPresentation({
  presentation,
  isFullscreen: true,
  loadingBackgroundColor: theme.colors.background,
});
```

Now, I'm working on add a new subscription plan which is between free and our premium one.

After a subscription to this intermediate plan, if I access to the premium paywall (by pressing a button in our app), it appear nicely but when I closed it, I'm facing this crash...

I don't have any more logs or details 😞   

<img src="https://github.com/Purchasely/Purchasely-ReactNative/assets/7771083/8d1e17e6-c26e-4095-9318-5ed33b4d4ef9" width="250">
<br>
<br>

I tried to display paywall with `presentPresentationForPlacement` like this:
```
const result = await Purchasely.presentPresentationForPlacement({
  placementVendorId,
  isFullscreen: true,
  loadingBackgroundColor: theme.colors.background,
});
```
And it works almost fine, but we doesn't have prices displayed on paywalls on android with this.. 😞

**Comment by kherembourg** [comment]
Hello @SialB 
Sorry for the late reply

Do you still have this issue? If yes, can you please contact me directly so that I check with you directly?
Thank you
