### ISSUE TITLE
[Play Store] Support for multiple base plans and offers

### ISSUE THREAD

**Issue by hatem-72** [Purchasely/Purchasely-ReactNative#55]
From what I read in the [documentation](https://docs.purchasely.com/quick-start-1/console-configuration/create-your-products/play-store#creating-a-new-subscription-in-the-google-play-store-console), Purchasely fits well with the legacy Play Store subscription system but I see no mention to the new system providing multiple base plans and offers for a single product.

Is it supported ?
In addition, what's the status of support for Google Play Billing Library v5 and v6?

Here are some refs:
https://support.google.com/googleplay/android-developer/answer/12124625
https://developer.android.com/google/play/billing/compatibility

**Comment by kherembourg** [comment]
Hello
It is not supported yet but will be in the coming weeks with the support of Google Play Billing v5 in our ReactNative SDK 3.0
