### ISSUE TITLE
These are unsupported versions of Google Play Billing.

### ISSUE THREAD

**Issue by clementnv** [Purchasely/Purchasely-ReactNative#57]
Hello here,

Today it's **impossible to pubish an app on the play store** with the SDK, we have an error :

![Capture d’écran 2023-08-11 à 10 48 52](https://github.com/Purchasely/Purchasely-ReactNative/assets/36882039/9176710d-3094-40d3-9a13-e2fea9f3d790)

Can you upgrade the biling version ?

Thank you ! 🙏

**Comment by clementnv** [comment]
ping @kherembourg 🙏

**Comment by kherembourg** [comment]
Hello @clementnv 
We have just released our version 4 today with Google Play Billing v5, please try it but be aware that documentation won't be available before September
https://github.com/Purchasely/Purchasely-ReactNative/releases/tag/4.0.0

**Comment by clementnv** [comment]
Thank you ! 

I try only on Android and it's work fine, with the sample it's perfect to check change 🎉
